name: PR Test for SGL-KERNEL-NPU (Ascend NPU)

on:
  pull_request:
    branches: [ main ]
    paths:
      - "build.sh"
      - "cmake/**"
      - "python/**"
      - "csrc/**"
      - "test/**"
      - "scripts/**"
      - ".github/workflows/pr-test-npu.yml"
  workflow_dispatch:

concurrency:
  group: pr-test-npu-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-all-build:
    if: (github.repository == 'sgl-project/sgl-kernel-npu' || github.event_name == 'pull_request') &&
        github.event.pull_request.draft == false
    runs-on: linux-aarch64-a3-16
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.3.rc1-a3-ubuntu22.04-py3.11
    steps:
      - name: Clean git config
        run: |
          CONFIG_KEY='http.https://gh-proxy.test.osinfra.cn/.extraheader'
          git config --global --unset "$CONFIG_KEY" || true

      - name: Clean workspace
        run: |
          sudo rm -rf --one-file-system "$GITHUB_WORKSPACE"/* "$GITHUB_WORKSPACE"/.* 2>/dev/null || true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Install dependencies
        run: |
          # speed up by using infra cache services
          CACHING_URL="cache-service.nginx-pypi-cache.svc.cluster.local"
          sed -Ei "s@(ports|archive).ubuntu.com@${CACHING_URL}:8081@g" /etc/apt/sources.list
          pip config set global.index-url http://${CACHING_URL}/pypi/simple
          pip config set global.trusted-host ${CACHING_URL}

          bash scripts/npu_ci_install_dependency.sh

      - name: Prepare Deepep
        run: bash scripts/prepare_deepep_in_container.sh

      - name: Run test intranode
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 2300
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_intranode.py

      - name: Run test multi-round intranode
        timeout-minutes: 10
        env:
          DEEPEP_NORMAL_LONG_SEQ_ROUND: 5
          DEEPEP_NORMAL_LONG_SEQ_PER_ROUND_TOKENS: 512
          HCCL_BUFFSIZE: 1000
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_intranode.py --num-tokens=2122

      - name: Run test low latency
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 1913
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_low_latency.py

      - name: Run test base fused deep moe
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 2000
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 2
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 2 --num-experts 256
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 48 --num-experts 128
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 48 --num-experts 256

      - name: Run test muti-model for fused deep moe
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 2000
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 2 --num-experts 256 --hidden 6144 --moe-intermediate-size 2048
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 48 --num-experts 128 --hidden 6144 --moe-intermediate-size 2048
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 2 --num-experts 256 --hidden 4096 --moe-intermediate-size 1536
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 48 --num-experts 256 --hidden 4096 --moe-intermediate-size 1536
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 48 --num-experts 128 --hidden 4096 --moe-intermediate-size 1536

      - name: Run test fused deepep moe eplb
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 2000
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --topk-drop-col 3
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --topk-drop-prob 0.3
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 2 --topk-drop-col 2
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 2 --topk-drop-col 3 --num-experts 16
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 4 --topk-drop-col 1 --num-experts 32

      - name: Run test mixed running
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 3000
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_normal_and_low_latency.py

      - name: Run test generalization of fused deep moe
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 2048
        run: bash scripts/generalization_test_fused_deep_moe.sh

  test-build-deepep:
    if: (github.repository == 'sgl-project/sgl-kernel-npu' || github.event_name == 'pull_request') &&
        github.event.pull_request.draft == false
    runs-on: linux-aarch64-a3-16
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.3.rc1-a3-ubuntu22.04-py3.11
    steps:
      - name: Clean git config
        run: |
          CONFIG_KEY='http.https://gh-proxy.test.osinfra.cn/.extraheader'
          git config --global --unset "$CONFIG_KEY" || true

      - name: Clean workspace
        run: |
          sudo rm -rf --one-file-system "$GITHUB_WORKSPACE"/* "$GITHUB_WORKSPACE"/.* 2>/dev/null || true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Install dependencies
        run: |
          # speed up by using infra cache services
          CACHING_URL="cache-service.nginx-pypi-cache.svc.cluster.local"
          sed -Ei "s@(ports|archive).ubuntu.com@${CACHING_URL}:8081@g" /etc/apt/sources.list
          pip config set global.index-url http://${CACHING_URL}/pypi/simple
          pip config set global.trusted-host ${CACHING_URL}

          bash scripts/npu_ci_install_dependency.sh

      - name: Prepare Deepep
        run: bash scripts/prepare_deepep_in_container.sh -a deepep

      - name: Run test intranode
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 2300
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_intranode.py

      - name: Run test low latency
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 1913
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_low_latency.py

      - name: Run test base fused deep moe
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 2000
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 2
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 2 --num-experts 256
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 48 --num-experts 128
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 48 --num-experts 256

      - name: Run test muti-model for fused deep moe
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 2000
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 2 --num-experts 256 --hidden 6144 --moe-intermediate-size 2048
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 48 --num-experts 128 --hidden 6144 --moe-intermediate-size 2048
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 2 --num-experts 256 --hidden 4096 --moe-intermediate-size 1536
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 48 --num-experts 256 --hidden 4096 --moe-intermediate-size 1536
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 48 --num-experts 128 --hidden 4096 --moe-intermediate-size 1536

      - name: Run test fused deepep moe eplb
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 2000
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --topk-drop-col 3
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --topk-drop-prob 0.3
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 2 --topk-drop-col 2
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 2 --topk-drop-col 3 --num-experts 16
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_fused_deep_moe.py --num-tokens 4 --topk-drop-col 1 --num-experts 32

      - name: Run test mixed running
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 3000
        run: |
          python3 $GITHUB_WORKSPACE/tests/python/deepep/test_normal_and_low_latency.py

      - name: Run test generalization of fused deep moe
        timeout-minutes: 10
        env:
          HCCL_BUFFSIZE: 2048
        run: bash scripts/generalization_test_fused_deep_moe.sh

  test-build-deepep-internode:
    name: multi-node
    if: ${{ (github.repository == 'sgl-project/sglang' || github.event_name == 'pull_request') }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        test_config:
          - name: test_internode_a2
            node_size: 2
            test_case: tests/python/deepep/test_internode_a2.py
    uses: ./.github/workflows/internode.yml
    with:
      soc_version: a2
      runner: linux-amd64-cpu-0
      image: 'swr.cn-southwest-2.myhuaweicloud.com/base_image/dockerhub/lmsysorg/sglang:cann8.3.rc2-910b-release1225'
      test_config_name: ${{ matrix.test_config.name }}
      node_size: ${{ matrix.test_config.node_size }}
      test_case: ${{ matrix.test_config.test_case }}

  finish:
    if: always()
    needs:
      - test-all-build
      - test-build-deepep
    runs-on: ubuntu-latest
    steps:
      - name: Check all dependent job statuses
        run: |
          results=(${{ join(needs.*.result, ' ') }})
          for result in "${results[@]}"; do
            if [ "$result" = "failure" ] || [ "$result" = "cancelled" ]; then
              echo "Job failed with result: $result"
              exit 1
            fi
          done
          echo "All jobs completed successfully"
          exit 0
